// Generated by scripts/generate-error-capture.mjs; do not edit.
(function() {
  'use strict';
  try {

  // 幂等 guard（v2.4.0+ Bug F 防御）：
  // micro-frontend 场景下，主应用 + 多个子应用都可能在 build 时注入本脚本。
  // 如果不防御，第二次注入会：
  //   1. 重置 __EARLY_ERRORS__ = [] → 丢失第一份脚本已收集的所有错误
  //   2. 覆盖 __flushEarlyErrors__ → 主 Logger 只能拿到最后一份脚本的 buffer
  //   3. 启动第二个 fallback timer → 第一个 timer 仍然到点开火 → 双轨上报回归
  // 因此：检测到已加载过就直接退出，保留全部既有状态。
  if (window.__EARLY_ERROR_CAPTURE_LOADED__) {
    return;
  }
  // A previous owner may remain after a host clears only the public flags.
  if (typeof window.__stopEarlyErrorCapture__ === 'function') {
    try { window.__stopEarlyErrorCapture__(); } catch (ignored) {}
  }
  window.__EARLY_ERROR_CAPTURE_LOADED__ = true;

  window.__EARLY_ERRORS__ = window.__EARLY_ERRORS__ || [];
  if (typeof window.__LOGGER_INITIALIZED__ !== 'boolean') {
    window.__LOGGER_INITIALIZED__ = false;
  }
  var __FALLBACK_TIMER__ = null;
  var __CHUNK_RELOAD_TIMER__ = null;

  var MAX_ERRORS = 50;
  var captureActive = false;
  var pendingFlushes = [];
  var captureStopped = false;

  var stopCapture = function(keepReload) {
    captureStopped = true;
    pendingFlushes = [];
    if (__FALLBACK_TIMER__ !== null) {
      clearTimeout(__FALLBACK_TIMER__);
      __FALLBACK_TIMER__ = null;
    }
    if (!keepReload && __CHUNK_RELOAD_TIMER__ !== null) {
      clearTimeout(__CHUNK_RELOAD_TIMER__);
      __CHUNK_RELOAD_TIMER__ = null;
    }
    try { window.removeEventListener('error', onEarlyError, true); } catch (ignored) {}
    try { window.removeEventListener('unhandledrejection', onEarlyRejection); } catch (ignored) {}
  };
  window.__stopEarlyErrorCapture__ = stopCapture;

  function finishCapture() {
    captureActive = false;
    if (captureStopped) return;
    var callbacks = pendingFlushes;
    pendingFlushes = [];
    for (var i = 0; i < callbacks.length; i++) {
      if (window.__stopEarlyErrorCapture__ !== stopCapture) break;
      try { flushEarlyErrors(callbacks[i]); }
      catch (ignored) { captureFailed(); }
    }
  }

  var deviceInfo = {
    ua: navigator.userAgent,
    lang: navigator.language,
    screen: screen.width + 'x' + screen.height,
    url: location.href,
    time: Date.now()
  };

  var normalizeEvidence = (function () {
/**
 * Self-contained so the build plugin can embed this exact implementation in
 * the standalone early script. No runtime imports or external closure state.
 * The 8 KiB budget applies to diagnostic graphs/extras, not primary message or
 * original stack: payload sanitization retains its existing reject/split policy.
 */
function normalizeErrorEvidence(input, options) {
    if (options === void 0) { options = {}; }
    var issues = [];
    var seen = [];
    var readsByObject = typeof WeakMap === 'function' ? new WeakMap() : undefined;
    var readObjects = [];
    var readCaches = [];
    var bytes = 8192;
    var nodes = 128;
    var isObject = function (v) {
        return v !== null && (typeof v === 'object' || typeof v === 'function');
    };
    var issue = function (path, kind) {
        var entry = path.slice(0, 120) + ':' + kind;
        if (issues.length < 16 && issues.indexOf(entry) === -1)
            issues.push(entry);
    };
    var read = function (obj, key, path) {
        if (!isObject(obj))
            return undefined;
        var cache;
        if (readsByObject) {
            cache = readsByObject.get(obj);
            if (!cache) {
                cache = Object.create(null);
                readsByObject.set(obj, cache);
            }
        }
        else {
            var index = readObjects.indexOf(obj);
            if (index >= 0)
                cache = readCaches[index];
            else {
                cache = Object.create(null);
                readObjects.push(obj);
                readCaches.push(cache);
            }
        }
        if (Object.prototype.hasOwnProperty.call(cache, key))
            return cache[key];
        var value;
        try {
            value = obj[key];
        }
        catch (_a) {
            issue(path, 'read-failed');
        }
        cache[key] = value;
        return value;
    };
    var primitive = function (v) {
        // Never call user-defined toString / valueOf / toJSON.
        if (isObject(v))
            return typeof v === 'function' ? '[function]' : '[object]';
        try {
            return String(v);
        }
        catch (_a) {
            return '[unreadable]';
        }
    };
    var isPlainObject = function (value, path) {
        try {
            var prototype = Object.getPrototypeOf(value);
            if (prototype === null || prototype === Object.prototype)
                return true;
            // A foreign realm has its own Object.prototype. Check the native
            // constructor without invoking a getter or user-defined conversion hook.
            if (Object.getPrototypeOf(prototype) !== null)
                return false;
            var constructor = Object.getOwnPropertyDescriptor(prototype, 'constructor');
            return typeof (constructor === null || constructor === void 0 ? void 0 : constructor.value) === 'function' &&
                Function.prototype.toString.call(constructor.value) === Function.prototype.toString.call(Object);
        }
        catch (_a) {
            issue(path, 'reflection-failed');
            return false;
        }
    };
    var isErrorObject = function (value) {
        try {
            if (value instanceof Error)
                return true;
            var prototype = Object.getPrototypeOf(value);
            // Cross-realm built-in errors and their subclasses inherit a native
            // Error.prototype. Descriptors avoid constructor/toStringTag getters.
            var nativeError = Function.prototype.toString.call(Error);
            for (var depth = 0; prototype && depth < 32; depth++) {
                var constructor = Object.getOwnPropertyDescriptor(prototype, 'constructor');
                if (typeof (constructor === null || constructor === void 0 ? void 0 : constructor.value) === 'function' &&
                    Function.prototype.toString.call(constructor.value) === nativeError)
                    return true;
                prototype = Object.getPrototypeOf(prototype);
            }
            if (prototype)
                issue('error', 'prototype-depth');
        }
        catch (_a) {
            issue('error', 'reflection-failed');
        }
        return false;
    };
    var text = function (value, path) {
        var end = 0;
        var used = 0;
        while (end < value.length) {
            var c = value.charCodeAt(end);
            var pair = c >= 0xd800 && c <= 0xdbff && end + 1 < value.length &&
                value.charCodeAt(end + 1) >= 0xdc00 && value.charCodeAt(end + 1) <= 0xdfff;
            var size = pair ? 4 : c < 0x80 ? 1 : c < 0x800 ? 2 : 3;
            if (used + size > bytes)
                break;
            used += size;
            end += pair ? 2 : 1;
        }
        bytes -= used;
        if (end < value.length)
            issue(path, 'truncated');
        return value.slice(0, end);
    };
    // Primary protocol fields and structured original frames bypass diagnostic
    // size/count limits. PayloadSanitize owns their final reject/split policy.
    // Safe reads, cycle protection and the depth guard still apply.
    var snapshot = function (value, path, depth, primary) {
        if (primary === void 0) { primary = false; }
        if (!primary) {
            nodes--;
            // Sentinels are structural diagnostics, not captured string content.
            // Charge their node, but preserve them even after the content budget is
            // exhausted. Otherwise a second pass turns '[circular]' into '[c'.
            if (value === '[truncated]' || value === '[circular]' || value === '[unreadable]')
                return value;
            if (nodes < 0 || bytes <= 0) {
                issue(path, 'budget');
                return '[truncated]';
            }
        }
        if (typeof value === 'string')
            return primary ? value : text(value, path);
        if (!isObject(value)) {
            if (value === null || typeof value === 'boolean' || typeof value === 'number')
                return value;
            return primary ? primitive(value) : text(primitive(value), path);
        }
        if (seen.indexOf(value) !== -1) {
            issue(path, 'circular');
            return '[circular]';
        }
        if (depth >= 4) {
            issue(path, 'depth');
            return '[truncated]';
        }
        seen.push(value);
        try {
            if (Array.isArray(value)) {
                var length = read(value, 'length', path + '.length');
                var validLength = typeof length === 'number' && length >= 0 && length <= 4294967295 && Math.floor(length) === length;
                if (!validLength)
                    issue(path, 'invalid-length');
                var count = validLength ? (primary ? length : Math.min(length, 8)) : 0;
                if (!primary && typeof length === 'number' && length > 8)
                    issue(path, 'items');
                var out_1 = [];
                for (var i = 0; i < count; i++)
                    out_1.push(snapshot(read(value, i, path + '[' + i + ']'), path + '[' + i + ']', depth + 1, primary));
                return out_1;
            }
            // Only enumerate plain objects. Error-like/host objects use fixed fields.
            var plain = isPlainObject(value, path);
            var keys_1 = ['name', 'message', 'stack', 'code', 'cause', 'errors'];
            if (plain) {
                try {
                    keys_1 = Object.keys(value);
                }
                catch (_a) {
                    issue(path, 'reflection-failed');
                }
            }
            if (!primary && keys_1.length > 32)
                issue(path, 'properties');
            var out = {};
            for (var _i = 0, _b = primary ? keys_1 : keys_1.slice(0, 32); _i < _b.length; _i++) {
                var key = _b[_i];
                if (key === 'toJSON' || key === '__proto__' || key === 'constructor' || key === 'prototype')
                    continue;
                if (!primary && (bytes <= 0 || nodes <= 0)) {
                    issue(path, 'budget');
                    break;
                }
                var field = read(value, key, path + '.' + key);
                if (field === undefined)
                    continue;
                // Never emit a prefix as a different business key. If the complete key
                // cannot fit, omit this and subsequent fields with an explicit marker.
                if (!primary && text(key, path + '.' + key) !== key) {
                    issue(path + '.' + key, 'key-budget');
                    break;
                }
                Object.defineProperty(out, key, {
                    value: snapshot(field, path + '.' + key, depth + 1, primary), enumerable: true, writable: true, configurable: true,
                });
            }
            return out;
        }
        catch (_c) {
            issue(path, 'reflection-failed');
            return '[unreadable]';
        }
        finally {
            seen.pop();
        }
    };
    var name = read(input, 'name', 'name');
    var message = read(input, 'message', 'message');
    var stack = read(input, 'stack', 'stack');
    var type = read(input, 'type', 'type');
    var value = read(input, 'value', 'value');
    var previous = read(input, 'evidence', 'evidence');
    var previousVersion = read(previous, 'schemaVersion', 'evidence.schemaVersion');
    var normalized = previousVersion === 1 && typeof type === 'string' && typeof value === 'string';
    var prior = function (key) { return normalized ? read(previous, key, 'evidence.' + key) : undefined; };
    var priorOrigin = prior('stackOrigin');
    var synthetic = options.synthetic === true || priorOrigin === 'capture-site';
    try {
        if (typeof Symbol !== 'undefined')
            synthetic = synthetic || read(input, Symbol.for('aemeath.syntheticStack'), 'syntheticStack') === true;
    }
    catch (_a) {
        issue('syntheticStack', 'read-failed');
    }
    var originalStack = !synthetic && priorOrigin !== 'unavailable' && typeof stack === 'string' && stack.trim() ? stack : undefined;
    var capture = synthetic && typeof stack === 'string' && stack.trim() ? stack : prior('captureStack');
    var originalName = typeof name === 'string' ? name : prior('originalName');
    var output = {
        type: typeof type === 'string' ? type : typeof name === 'string' ? name : 'Error',
        value: typeof value === 'string' ? value : typeof message === 'string' ? message : options.message !== undefined ? options.message : primitive(input),
    };
    if (originalStack)
        output.stack = originalStack;
    var source = options.source;
    var line = options.line;
    var column = options.column;
    var priorChannel = prior('captureChannel');
    var priorPhase = prior('capturePhase');
    var occurrence = prior('occurrenceId');
    var reasonKind = prior('reasonKind');
    var evidence = {
        schemaVersion: 1,
        captureChannel: options.channel || (typeof priorChannel === 'string' ? priorChannel : 'manual'),
        capturePhase: options.phase || (priorPhase === 'early' ? 'early' : 'runtime'),
        reasonKind: typeof reasonKind === 'string' ? reasonKind : input === null ? 'null' : typeof input,
        stackOrigin: originalStack ? 'original' : typeof capture === 'string' && capture ? 'capture-site' : 'unavailable',
        occurrenceId: typeof occurrence === 'string' && occurrence ? occurrence : 'err-' + Date.now().toString(36) + '-' + Math.random().toString(36).slice(2),
        normalization: { issues: issues },
    };
    if (typeof originalName === 'string' && (!synthetic || normalized))
        evidence.originalName = originalName;
    if (typeof capture === 'string' && capture)
        evidence.captureStack = text(capture, 'captureStack');
    if (!originalStack) {
        var oldReason = prior('missingStackReason');
        evidence.missingStackReason = oldReason === 'browser-redacted' || oldReason === 'reason-without-stack' ? oldReason :
            evidence.captureChannel === 'global' && output.value === 'Script error.' && !source && !line && !column ? 'browser-redacted' : 'reason-without-stack';
    }
    if (source !== undefined || line !== undefined || column !== undefined)
        evidence.browserLocation = { source: source, line: line, column: column };
    else {
        var location = prior('browserLocation');
        if (isObject(location))
            evidence.browserLocation = snapshot(location, 'browserLocation', 0, true);
    }
    var objectId = prior('errorObjectId');
    if (typeof objectId === 'string')
        evidence.errorObjectId = objectId;
    if (normalized) {
        var oldIssues = read(prior('normalization'), 'issues', 'normalization.issues');
        try {
            if (Array.isArray(oldIssues)) {
                // Input arrays can override slice, species and iteration. Only inspect
                // bounded indexes through the same guarded, once-per-property reader.
                var length = read(oldIssues, 'length', 'normalization.issues.length');
                var count = typeof length === 'number' && length >= 0 && Math.floor(length) === length ? Math.min(length, 16) : 0;
                for (var i = 0; i < count; i++) {
                    var item = read(oldIssues, i, 'normalization.issues[' + i + ']');
                    if (typeof item === 'string' && issues.length < 16 && issues.indexOf(item) < 0)
                        issues.push(item);
                }
            }
        }
        catch (_b) {
            issue('normalization', 'read-failed');
        }
    }
    var protocolFields = ['source', 'filename', 'lineno', 'colno', 'earlyError', 'captureTimestamp',
        'device', 'tagName', 'src', 'outerHTML', '_isAemeathInternalError', 'stacktrace'];
    // Unlabelled object reasons have one canonical diagnostic graph. Copying
    // their fields to the root as well spends the same budget twice, including
    // when Logger normalizes again or an early snapshot crosses JSON transport.
    var objectReason = isObject(input) && typeof message !== 'string' &&
        typeof value !== 'string' && options.message === undefined && !isErrorObject(input);
    var skip = ['name', 'message', 'stack', 'type', 'value', 'evidence', 'toJSON', '__proto__', 'constructor', 'prototype'].concat(protocolFields);
    var keys = ['code', 'cause', 'errors'];
    if (isObject(input)) {
        // Error own extensions are a public compatibility surface. Do not enumerate
        // arbitrary host objects (DOM/Bridge); only plain and Error-like objects.
        try {
            if (!objectReason && (isPlainObject(input, 'error') || isErrorObject(input))) {
                keys = keys.concat(Object.getOwnPropertyNames(input).filter(function (k) { return keys.indexOf(k) < 0; }));
            }
        }
        catch (_c) {
            issue('error', 'reflection-failed');
        }
        seen.push(input);
        // Read these independently of root property order/count as well as bytes.
        for (var _i = 0, protocolFields_1 = protocolFields; _i < protocolFields_1.length; _i++) {
            var key = protocolFields_1[_i];
            if (key === 'stacktrace' && synthetic)
                continue;
            var field = read(input, key, key);
            if (field !== undefined)
                output[key] = snapshot(field, key, 0, true);
        }
        // Protocol fields do not consume diagnostic extension slots, including
        // type/value/evidence added during a preceding normalization pass.
        keys = keys.filter(function (key) { return skip.indexOf(key) < 0; });
        if (keys.length > 40)
            issue('error', 'properties');
        for (var _d = 0, _e = objectReason ? [] : keys.slice(0, 40); _d < _e.length; _d++) {
            var key = _e[_d];
            var field = read(input, key, key);
            if (field !== undefined)
                output[key] = snapshot(field, key, 0);
        }
        seen.pop();
    }
    // Object reasons keep a safe representation instead of JSON.stringify(reason).
    if (objectReason) {
        var reason = snapshot(input, 'reason', 0);
        output.reason = reason;
        try {
            output.value = JSON.stringify(reason) || '[object]';
        }
        catch (_f) {
            output.value = '[unreadable]';
        }
    }
    output.evidence = evidence;
    return output;
}

return normalizeErrorEvidence;
})();

  function captureFailed() {
    try {
      window.__AEMEATH_EARLY_CAPTURE_FAILURES__ = Math.min(2147483647,
        (window.__AEMEATH_EARLY_CAPTURE_FAILURES__ || 0) + 1);
    } catch (ignored) {}
  }

  function addError(error) {
    if (captureStopped || window.__LOGGER_INITIALIZED__) return;
    if (window.__EARLY_ERRORS__.length >= MAX_ERRORS) return;

    var normalized = normalizeEvidence(error.reason, {
      channel: error.type === 'error' ? 'global' : error.type,
      phase: 'early', message: error.message,
      source: error.filename || error.source, line: error.lineno, column: error.colno
    });
    // Getters may change lifecycle state or the public buffer while reading.
    if (captureStopped || window.__LOGGER_INITIALIZED__) return;
    if (window.__EARLY_ERRORS__.length >= MAX_ERRORS) return;
    window.__EARLY_ERRORS__.push({
      type: error.type,
      message: normalized.value,
      stack: normalized.stack || null,
      error: normalized,
      filename: error.filename,
      lineno: error.lineno,
      colno: error.colno,
      source: error.source,
      // Legacy standalone/IIFE consumers read these resource fields from context.
      tagName: error.tagName,
      src: error.src,
      timestamp: Date.now(),
      device: deviceInfo
    });
  }

  function onEarlyError(event) {
    if (captureStopped || captureActive || window.__LOGGER_INITIALIZED__) return;
    captureActive = true;
    try {
    if (captureStopped || window.__LOGGER_INITIALIZED__) return;
    var target = event.target || event.srcElement;

    if (target && target !== window && target.tagName) {
      addError({
        type: 'resource',
        message: 'Resource load failed',
        tagName: target.tagName,
        src: target.src || target.href || '',
        source: target.src || target.href,
        filename: target.src || target.href,
        stack: null
      });

    } else {
      addError({
        type: 'error',
        message: event.message || 'Unknown error',
        filename: event.filename || '',
        lineno: event.lineno || 0,
        colno: event.colno || 0,
        reason: event.error
      });
    }
    } catch (captureFailure) { captureFailed(); }
    finally { finishCapture(); }
  }
  window.addEventListener('error', onEarlyError, true);

  function onEarlyRejection(event) {
    if (captureStopped || captureActive || window.__LOGGER_INITIALIZED__) return;
    captureActive = true;
    try {
    if (captureStopped || window.__LOGGER_INITIALIZED__) return;
    addError({ type: 'unhandledrejection', reason: event.reason });
    } catch (captureFailure) { captureFailed(); }
    finally { finishCapture(); }
  }
  window.addEventListener('unhandledrejection', onEarlyRejection);


  var flushEarlyErrors = function(callback) {
    if (window.__stopEarlyErrorCapture__ !== stopCapture) return;
    if (typeof callback !== 'function') return;
    // A getter can initialize Logger synchronously. Finish the observation
    // before transferring ownership so it is included exactly once.
    if (captureActive) { pendingFlushes.push(callback); return; }
    window.__LOGGER_INITIALIZED__ = true;
    stopCapture();
    var errors = window.__EARLY_ERRORS__.slice();
    window.__EARLY_ERRORS__ = [];
    try {
      callback(errors);
    } catch (e) {
      try { console.error('[EarlyErrorCapture] Error in flush callback:', e); } catch (ignored) {}
    }
  };
  window.__flushEarlyErrors__ = flushEarlyErrors;

  // __EARLY_ERROR_CAPTURE_LOADED__ 已在脚本顶部 set，无需在末尾重复。
  // 如果走到这里，说明 listeners 都已注册成功，整个脚本初始化通过。

  } catch (__earlyErr__) {
    try {
      if (window.__stopEarlyErrorCapture__ === stopCapture) {
        stopCapture();
        delete window.__stopEarlyErrorCapture__;
        delete window.__EARLY_ERROR_CAPTURE_LOADED__;
        if (window.__flushEarlyErrors__ === flushEarlyErrors) delete window.__flushEarlyErrors__;
      }
    } catch (ignored) {}
    try { console.error('[EarlyErrorCapture] Script init error:', __earlyErr__); } catch (e) {}
  }
})();
